version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:10.16.3 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: The First Step
          command: |
            echo "Hello world!"
            echo "This is the delivery pipeline" 
      - run:
          command: |
            ls -al
            echo "^^^^That should look familiar^^^^"
      - run:
          name: Install packages
          command: |
            npm i
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test