name: PR Checks

on: pull_request

jobs:
  build_id:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set build id'
        id: build_id
        run: echo "::set-output name=id::$date +%s)"
      - name: 'Cache .build-id'
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}/.build-id
          key: ${{ runner.os }}-build-id-${{ github.head_ref }}-${{ github.sha }}-${{ steps.build_id.outputs.id }}
      - name: 'Save build id'
        run: |
          mkdir -p .build-id 
          echo $BUILD_ID > .build-id/id
        env:
          BUILD_ID: ${{ steps.build_id.outputs.id }}

  