name: End-to-end tests
on: [pull_requests]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          spec: cypress/integration/examples/actions.spec.js
          start: npm run test:e2e:ci
          wait-on: http://localhost:3030
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}