name: PR Checks

on: pull_request

jobs:
  run_pr_check:
    name: EMF PR Checks
    runs-on: ubuntu-16.04
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install Dependencies
      run: npm install
    - name: Run End-to-end tests
      uses: cypress-io/github-action@v1

  # - run: npm ci
  # - run: npm run build --if-present
  # - run: npm test
  #   env:
  #     CI: true