name: PR Checks

on: pull_request

jobs:
  run_pr_check:
    name: EMF PR Checks
    runs-on: ubuntu-16.04
    # runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        # machines: [1, 2, 3]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache NPM dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-cache-
    - name: Install Dependencies
      run: npm install
    
  run_e2e_tests:
    needs: run_pr_check
      name: Run End-to-end tests
      runs-on: ubuntu-16.04
      strategy:
        fail-fast: false
        matrix:
          machines: [1, 2 ,3]
    - steps:
        # - name: Checkout
        #   uses: actions/checkout@v1
        - name: Cypress run
          uses: cypress-io/github-action@v1
          timeout-minutes: 10
          with:
            record: true
            parallel: true
            group: 'Cypress group example'
            # build: npm run test:e2e:ci
            start: npm run test:e2e:ci
            wait-on: http://localhost:8000
          env:
            CYPRESS_RECORD_KEY: ${{ secrets.dashboardRecordKey }}

  # - run: npm ci
  # - run: npm run build --if-present
  # - run: npm test
  #   env:
  #     CI: true